### ISSUE TITLE
Lab 2 Peer Review by Yoan BOUTE s321389

### ISSUE THREAD

**Issue by YoanBoute** [S309100/CI2324#1]
Hi, I will review your work on the Nim game and evolutionary strategies.
Your work is good, but there are some elements missing :
- The most important problem is that you don't use evolution : you implemented well population, mutation and offspring, but the parameter you're trying to optimize is never used in your evolved_strategy. You mention bias is a probability, but it has no impact on the move that is made, so your evolution strategy is just a rule-based strategy. At least, you could have used this bias to impact the default random move made if no spicy move is found. 
- In your evolved_strategy, you always try to switch the value of the Boolean (ns == 0), but this leads nowhere : depending on the version of Nim you want to play to, your goal is either to always have ns == 0, or always have ns != 0. By switching its value, you give the opponent the advantage at least half of the times
- Regarding the optimal rule-based strategy, you made almost no change to the one given in the template. This strategy can be improved, for example by trying to let the less number of good moves to the opponent
- Finally, your code presents no results on the strategies you used, so we can't see whether they reached the goal or not
So the code is overall good, but it is very unfortunate that the evolution strategies you use optimize a non-existing parameter.

**Comment by SamiSani68** [comment]
Thank you for your detailed review and valuable feedback. I appreciate your insights, and I agree that there are areas for improvement in the code. I will address each of the points you raised:

Evolutionary Strategy Parameter Usage:
You're absolutely right; I overlooked the crucial step of utilizing the evolved parameter in the evolved_strategy function. I will make the necessary modifications to incorporate the evolved parameter into the move decision process. This should involve using the bias to influence the choice of moves, especially in scenarios where no "spicy" move is found.

Handling of Nim-Sum Value:
I see the confusion in the handling of the nim-sum value. I will review and clarify the logic to ensure that the goal, whether it's always having ns == 0 or ns != 0, is properly addressed. Switching the value without a clear objective is counterproductive, and I'll make the necessary adjustments to address this.

Optimal Rule-Based Strategy:
Your feedback on the optimal rule-based strategy is well-taken. I will revisit the strategy and explore ways to enhance it, possibly by considering moves that limit the opponent's good moves. I'll strive to make the strategy more effective and strategic.

Results Presentation:
I recognize the importance of presenting results for the strategies used. I will implement a reporting mechanism to display the performance and outcomes of the strategies, allowing for a clearer evaluation of their effectiveness.

I appreciate your guidance, and I'll work on these improvements promptly. If you have any further suggestions or specific aspects you'd like me to focus on during the refinement, please let me know.

Thank you again for your time and feedback.
